NOTICE (Mar 22 2017):
We plan to cease support for the FTP protocol for file downloads as of
September 4, 2017, because it is insecure. ftp.gnu.org will continue to offer
downloads via HTTPS.

If you currently have automated scripts that download GNU packages through FTP
please update them to use HTTPS instead.

--

If you have any problems with the GNU software or its downloading,
please refer your questions to <gnu@gnu.org>.

There are several mirrors of this archive, a complete list can be
found on http://www.gnu.org/order/ftp.html.  You might want to use a
mirror closer to you.

Non-GNU programs that were formerly in gnu/ have moved to gnu/non-gnu/.
Most of them were just pointers in the format program.README.  If you
are looking for such a file, be sure to check gnu/non-gnu/.

Archives of the GNU mailing lists can be accessed or downloaded
via the web from http://mail.gnu.org; they are no longer available
by ftp.

The FSF provides this archive as a service to GNU users.  Please
consider donating to the FSF at http://donate.fsf.org/ or becoming an
Associate Member at http://member.fsf.org/.
